<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'Softtodo\\Candidateresume\\Controller\\CandidateController' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Controller/CandidateController.php',
    'Softtodo\\Candidateresume\\Controller\\EducationController' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Controller/EducationController.php',
    'Softtodo\\Candidateresume\\Controller\\ExperienceController' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Controller/ExperienceController.php',
    'Softtodo\\Candidateresume\\Controller\\LanguageController' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Controller/LanguageController.php',
    'Softtodo\\Candidateresume\\Controller\\SkillController' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Controller/SkillController.php',
    'Softtodo\\Candidateresume\\Domain\\Model\\Candidate' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Model/Candidate.php',
    'Softtodo\\Candidateresume\\Domain\\Model\\Education' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Model/Education.php',
    'Softtodo\\Candidateresume\\Domain\\Model\\Experience' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Model/Experience.php',
    'Softtodo\\Candidateresume\\Domain\\Model\\Language' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Model/Language.php',
    'Softtodo\\Candidateresume\\Domain\\Model\\Skill' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Model/Skill.php',
    'Softtodo\\Candidateresume\\Domain\\Repository\\CandidateRepository' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Repository/CandidateRepository.php',
    'Softtodo\\Candidateresume\\Domain\\Repository\\EducationRepository' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Repository/EducationRepository.php',
    'Softtodo\\Candidateresume\\Domain\\Repository\\ExperienceRepository' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Repository/ExperienceRepository.php',
    'Softtodo\\Candidateresume\\Domain\\Repository\\LanguageRepository' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Repository/LanguageRepository.php',
    'Softtodo\\Candidateresume\\Domain\\Repository\\SkillRepository' => $typo3InstallDir . 'typo3conf/ext/candidateresume/Classes/Domain/Repository/SkillRepository.php',
);
